[Core] Support OpenAssetIO 1.0.0-beta.1.0
OpenAssetIO/usdOpenAssetIOResolver pull request #33
Opened 2023-10-20 19:43 UTC by feltech

Update to use non-deprecated `TraitsData` header/namespace.

Fix expected exception type.

2023-10-23 09:46 UTC, foundrytom requested changes

2023-10-23 09:46 UTC, foundrytom commented on src/resolver.cpp
> +#include <openassetio/trait/TraitsData.hpp>
[Fix] Sorry no where else to put this, be good to add a `hasCapability` check at L211

2023-10-23 15:58 UTC, feltech commented on src/resolver.cpp
> +#include <openassetio/trait/TraitsData.hpp>
Added, along with a way to test it, in 9c9fb6fc

2023-11-01 07:36 UTC, elliotcmorris approved these changes
Had to go to some lengths to test the hasCapability check there. Took me a while to digest that. Good thinking though.

2023-11-01 11:55 UTC, foundrytom approved these changes
Thanks, LGTM FFTSAMAYL

2023-11-02 10:25 UTC, merged